version: '3.8'

services:
  db:
    container_name: book-creator-db
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: host.docker.internal
      # POSTGRES_HOST: 0.0.0.0
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pb_pgdata:/var/lib/postgresql/data/

volumes:
  pb_pgdata:
