name: mermese
on:
  push:
    branches:
      - main
jobs:
  my-testings:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo ...
        uses: actions/checkout@v4

      - name: List current folders
        run: ls -la

      - name: Check aws
        run: aws --version
