name: mermese
on:
  push:
    branches:
      - main
jobs:
  my-testings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print test message
        run: echo "test github actions test"
